apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        role: node1
        tier: web
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: magento2-web
        image: gonchare.azurecr.io/nginx:latest
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        resources:
          limits:
            memory: "256Mi"
            cpu: "10m"
        ports:
        - containerPort: 8087
        volumeMounts:
        - name: code
          mountPath: /magento2ce
          readOnly: false
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/magento.conf
          subPath: magento.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: code
        persistentVolumeClaim:
          claimName: code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  replicas: 2
  template:
    metadata:
      labels:
        app: php
        role: node1
        tier: php
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: magento2-php
        image: gonchare.azurecr.io/php:7.2
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: code
          mountPath: /magento2ce
          readOnly: false
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: esnode
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: es-cluster
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: "256Mi"
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-config
              key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-config
        configMap:
          name: es-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
      - name: es-data
        persistentVolumeClaim:
          claimName: es-data

