trigger:
- 2.3

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.2

steps:

- checkout: self
  clean: false
  fetchDepth: 1
  lfs: false

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

# - task: Kubernetes@1
#   displayName: 'Create nginx configMap'
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     azureResourceGroup: 'Trial'
#     kubernetesCluster: 'magento22'
#     configMapName: 'nginx-config'
#     forceUpdateConfigMap: true
#     useConfigMapFile: true
#     configMapFile: 'docker/images/web/magento.conf'

# - task: Kubernetes@1
#   displayName: 'Create elasticsearch configMap'
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     azureResourceGroup: 'Trial'
#     kubernetesCluster: 'magento22'
#     configMapName: 'es-config'
#     forceUpdateConfigMap: true
#     useConfigMapFile: true
#     configMapFile: 'docker/images/elasticsearch/elasticsearch.yml'

- task: Kubernetes@1
  displayName: 'Create code changes apply file'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    configMapName: 'code-changes-apply'
    forceUpdateConfigMap: true
    useConfigMapFile: true
    configMapFile: 'k8s-config/scripts/apply_changes.sh'

- task: Kubernetes@1
  displayName: 'Create magento install file'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    configMapName: 'install-magento'
    forceUpdateConfigMap: true
    useConfigMapFile: true
    configMapFile: 'k8s-config/scripts/install_magento.sh'

# - task: HelmInstaller@1
#   inputs:
#     helmVersionToInstall: 'latest'

# - task: HelmDeploy@0
#   displayName: 'Helm init'
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     azureResourceGroup: 'Trial'
#     kubernetesCluster: 'magento22'
#     command: 'init'
#     canaryImage: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '.git'

- task: ArchiveFiles@2
  displayName: 'Archive code'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

            # - task: AzureCLI@1
            #   displayName: 'Copy code to Azure File Storage'
            #   inputs:
            #     # azureSubscription: 'azureFileStorage'
            #     azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
            #     scriptLocation: 'inlineScript'
            #     inlineScript: 'az storage file upload --share-name magento.zip --source $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip --connection-string {{.azureFileStorageConnectionString}}'

- task: Kubernetes@1
  displayName: 'Provision deployment pod'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'apply'
    arguments: '-f k8s-config/deployment-pod.yaml --wait --force'

- script: sleep 5
  displayName: 'sleep'

- task: Kubernetes@1
  displayName: 'Copy code in deployment pod'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'cp'
    arguments: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip code:/magento.zip'

- task: Kubernetes@1
  displayName: 'Apply code changes'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'exec'
    arguments: '-i code bash /etc/scripts/apply_changes.sh'

# - task: HelmDeploy@0
#   displayName: 'Helm upgrade'
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     azureResourceGroup: 'Trial'
#     kubernetesCluster: 'magento22'
#     command: 'upgrade'
#     arguments: '--install --cleanup-on-fail --force'
#     chartType: 'Name'
#     chartName: 'magento2-helm'
#     recreate: true
#     resetValues: true

# - task: Kubernetes@1
#   displayName: 'Install Magento'
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     azureResourceGroup: 'Trial'
#     kubernetesCluster: 'magento22'
#     command: 'exec'
#     arguments: '-i code bash /etc/scripts/install_magento.sh'
