# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- 2.3

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.2

steps:
#- script: composer install --no-interaction --prefer-dist
#  displayName: 'composer install'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: Kubernetes@1
  displayName: 'Create nginx configMap'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    configMapName: 'nginx-config'
    forceUpdateConfigMap: true
    useConfigMapFile: true
    configMapFile: 'docker/images/web/magento.conf'

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  displayName: 'Helm init'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'init'
    canaryImage: true

# - script: |
#     sudo update-alternatives --set php /usr/bin/php$(phpVersion)
#     sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
#     sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
#     sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
#     sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
#     sudo apt update
#     sudo apt install php-dev libmcrypt-dev php-pear
#     php -version
#   displayName: 'Use PHP version $(phpVersion)'

# - script: |
#     php /usr/bin/composer install --no-dev
#   displayName: 'composer install'

# - task: HelmDeploy@0
#   displayName: 'Helm package'
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     azureResourceGroup: 'Trial'
#     kubernetesCluster: 'magento22'
#     command: 'package'
#     chartType: 'Name'
#     chartName: 'magento2-helm'

# - script: az acr helm push --name {{.registryName}} --subscription "Free Trial" --resource-group trial --username {{.registryLogin}} --password {{.registryPassword}}
#   displayName: 'push package'

- task: ArchiveFiles@2
  displayName: 'Archive code'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# - task: AzureCLI@1
#   displayName: 'Copy code to Azure File Storage'
#   inputs:
#     # azureSubscription: 'azureFileStorage'
#     azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az storage file upload --share-name magento.zip --source $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip --connection-string {{.azureFileStorageConnectionString}}'

- task: Kubernetes@1
  displayName: 'Provision deployment pod'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'apply'
    arguments: '-f k8s-config/deployment-done.yaml'

- task: Kubernetes@1
  displayName: 'Copy code in deployment pod'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'cp'
    arguments: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip $(kubectl get pods -o=name -l app=code | sed "s/^.\{4\}//"):/magento.zip'


- task: Kubernetes@1
  displayName: 'Unarchive code in pod'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'exec'
    arguments: '-it $(kubectl get pods -o=name -l app=code | sed "s/^.\{4\}//") tar -xzf /magento.zip -C /magento2ce'

- task: Kubernetes@1
  displayName: 'Remove archive'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'exec'
    arguments: '-it $(kubectl get pods -o=name -l app=code | sed "s/^.\{4\}//") rm /magento.zip'

- task: Kubernetes@1
  displayName: 'Composer install'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'exec'
    arguments: '-it $(kubectl get pods -o=name -l app=code | sed "s/^.\{4\}//") $(cd /magento2ce && composer install)'

- task: HelmDeploy@0
  displayName: 'Helm upgrade'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Free Trial(1737ad8f-2c51-47d1-80a7-9afe269721c4)'
    azureResourceGroup: 'Trial'
    kubernetesCluster: 'magento22'
    command: 'upgrade'
    arguments: '--install --cleanup-on-fail --force'
    chartType: 'Name'
    chartName: 'magento2-helm'
    recreate: true
    resetValues: true
