apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
  labels:
    type: logs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /logs
    server: nfs.f22
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  selector:
    matchLabels:
      type: logs
  accessModes:
    - ReadWriteMany
  storageClassName: logs
  resources:
    requests:
      storage: 2Gi
