apiVersion: v1
kind: PersistentVolume
metadata:
  name: code
spec:
  capacity:
    storage: 2Gi
  storageClassName: code
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/magento/azure/magento2ce"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: code
  resources:
    requests:
      storage: 2Gi
