apiVersion: v1
kind: Pod
metadata:
  name: code
spec:
  containers:
  - name: code
    image: gonchare.azurecr.io/php:7.2
    resources:
      limits:
        memory: "32Mi"
        cpu: "1m"
    volumeMounts:
    - name: code
      mountPath: /magento2ce
      readOnly: false
  volumes:
  - name: code
    persistentVolumeClaim:
      claimName: code