apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: php
spec:
  selector:
    app: php
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  # type: NodePort
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
  # type: NodePort
  type: LoadBalancer