# Default values for magento2-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

web:
  replicaCount: 1
  image:
    repository: gonchare.azurecr.io
    name: my-nginx
    tag: latest
  volume:
    mountPath: /magento2ce
  resources:
    limits:
      memory: "256Mi"
      cpu: "10m"

php:
  replicaCount: 1
  image:
    repository: gonchare.azurecr.io
    name: php
    tag: 7.2
  resources:
    limits:
      memory: "128Mi"
      cpu: "10m"

elasticsearch:
  replicaCount: 1
  image:
    repository: docker.elastic.co/elasticsearch
    name: elasticsearch
    tag: 6.5.0
  volume:
    mountPath: /magento2ce
  resources:
    limits:
      memory: "128Mi"
      cpu: "10m"
  env:
    ES_JAVA_OPTS: "-Xms128m -Xmx128m"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
